CREATE TABLE [dbo].[RECOMENDADOR_B2B] (
    [RUT]                         VARCHAR (50)    NULL,
    [CA_NUMBER]                   VARCHAR (50)    NULL,
    [Q_LINEAS_RUT]                INT             NULL,
    [MOVIL]                       INT             NULL,
    [COD_PLAN]                    VARCHAR (50)    NULL,
    [TMM]                         DECIMAL (10, 2) NULL,
    [TMM_SIN_IVA]                 DECIMAL (10, 2) NULL,
    [EXCEDENTES_LOCAL]            DECIMAL (10, 2) NULL,
    [CANTIDAD_PASAPORTES]         INT             NULL,
    [PRESTACION_1]                VARCHAR (50)    NULL,
    [PRECIO_PRESTACION_1_SIN_IVA] DECIMAL (10, 2) NULL,
    [IVA_PRESTACION_1]            DECIMAL (10, 2) NULL,
    [PRESTACION_2]                VARCHAR (50)    NULL,
    [PRECIO_PRESTACION_2_SIN_IVA] DECIMAL (10, 2) NULL,
    [IVA_PRESTACION_2]            DECIMAL (10, 2) NULL,
    [TMM_PRESTACION_SIN_IVA]      DECIMAL (10, 2) NULL,
    [TMM_PRESTACION_IVA_INC]      DECIMAL (10, 2) NULL,
    [TMM+PRESTACION]              DECIMAL (11, 2) NULL,
    [BONO_PRESTACION_CANTIDAD]    BIGINT          NULL,
    [BONO_PLAN_CANTIDAD]          BIGINT          NULL,
    [BONO_DATOS_TOTAL]            BIGINT          NULL,
    [BONO_DATOS_TOTAL_PROM]       BIGINT          NULL,
    [MINUTOS_VOZ_OFF_PROM]        DECIMAL (10, 2) NULL,
    [MB_TOTAL]                    DECIMAL (10, 2) NULL,
    [MB_TOTAL_PROM]               DECIMAL (10, 2) NULL,
    [EXCEDENTES_ROAMING_DATOS]    DECIMAL (10, 2) NULL,
    [EXCEDENTES_ROAMING_SMS]      DECIMAL (10, 2) NULL,
    [EXCEDENTES_ROAMING_VOZ]      DECIMAL (10, 2) NULL,
    [EXCEDENTES_ROAMING]          DECIMAL (10, 2) NULL,
    [ROAMER]                      VARCHAR (50)    NULL,
    [COSTO_PASAPORTES]            DECIMAL (10, 2) NULL,
    [MONTO_DENTRO_CREDITO_PROM]   DECIMAL (10, 2) NULL,
    [ARPU_PROM]                   DECIMAL (12, 2) NULL,
    [ARPU_MAX]                    DECIMAL (10, 2) NULL,
    [FECHA_ARPU_MAX]              VARCHAR (50)    NULL,
    [ARPU_RUT_MAX]                DECIMAL (10, 2) NULL,
    [FECHA_ARPU_RUT_MAX]          VARCHAR (50)    NULL,
    [ARPU_ROAMER_PROM]            DECIMAL (10, 2) NULL,
    [ROAMER_PROM]                 VARCHAR (9)     NOT NULL,
    [PLAN_SUGERIDO]               VARCHAR (50)    NULL,
    [PLAN_SUGERIDO_RETENCION]     VARCHAR (50)    NULL,
    [BONO_PLAN_SUGERIDO]          INT             NULL,
    [TMM_PLAN_SUGERIDO]           DECIMAL (10, 2) NULL,
    [BONO_PLAN_RETENCION]         INT             NULL,
    [TMM_PLAN_RETENCION]          DECIMAL (10, 2) NULL,
    [ROAMING_PLAN_SUGERIDO]       VARCHAR (50)    NULL,
    [ROAMING_PLAN_RETENCION]      VARCHAR (50)    NULL
);

